### ISSUE TITLE
Hey it's my final self evaluation

### ISSUE THREAD

**Issue by amberlbailey** [amberlbailey/portfolio#10]
@thomasjbradley
itsamber.ca

### **Goals** 
My goal was to break the barrier of boring serious portfolio sites. I wanted something that reflects my personality of being professional yet adding a humorous and fun twist.

### **Struggles** 
The main struggle was to find a happy medium between image quality and the speed performance of my website.

### **Successes** 
I feel like I proved myself of having some coding skills to create a website that I am proud of. By having this whole semester it allowed me to regain the coding ability that I lost in the summer. It was scary coming back to code an entire website but I have learned that if I set my mind to something I can accomplish it. With the help of diving back into previous web dev tutorials of course.

### **What I can improve on for next time** 
I feel like I just need to practice because practice makes perfect, especially in coding. I need to code every day so that for next time I'm not confused and frustrated with why the paragraph wasn't aligning properly.
  
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Details** | No sweating | Some details sweat | Sweat all the details | **Disgusting, dripping, sweaty details** |
| **Personality & design** | Bland, boring, just another graphic designer | Fairly generic, visual design could be pushed more | Quality layouts and unique, personable content & design | **Unique and recognizable as you, with engaging, personable content & design** |
| **Text content** | Fake content only | Some real content, some fake | All real content but with lots of errors | **Real content, well written, no grammar or spelling errors** |
| **Accessibility** | No considerations | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | **Accessibility is well considered and tested** |
| **Pages & images** | Barely started | Missing lots of pages & images | Has most of the pages, some placeholder images | **All pages exist and are well done with complete imagery** |
| **Image quality** | Only placeholder images | Some portfolio piece images | Lots of images but low quality | **High quality portfolio images — and lots of them** |
| **Responsiveness** | Not responsive | Works on some screens | Responsive but with lots of awkwardness |**Looks great on all screen sizes** |
| **Performance** | Mega slow… | Slow… | **Could load faster** | Blazing fast awesomeness |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | **Decent indentation, just a couple validation errors, decent semantics** | Well indented, fully valid, good semantics |

### 25/27

**Details** 
I spent most of the time trying to figure out the little details of the colorful explosions throughout my site without making it distract from my work. Once I created my logo I created a pattern to go along with it that I sprinkled throughout my site effectively. Making it a fun Easter egg hunt on where I put the pattern.

**Personality & design** 
It all started with my domain name and it lit the branding fire. No fancy names or fluff to explain my projects. Being very straightforward in just stating the obvious of what the project is about fits my personality and humor. 
The design itself I wanted it to look like a normal website but added the colour explosions to have the element of a fun surprise. This breaks the barrier of boring and plain and is something different that stands out against other portfolios.

**Text content** 
There is no placeholder text throughout my site and I re-read through all of my content to make sure that I had no spelling mistakes. As I do code at 3 am which is prime time for spelling mistakes. 

**Accessibility** 
When I start my design I focus on responsiveness than move on to accessibility. This time I wanted to make sure everyone can access my site with the help of skip links, alt tags, and roles. Making sure I hit all the checkboxes on the accessibility checklist.

**Pages & images** 
All the sketches, iterations and final photos are my own and I have cleaned them up the best I could to make them portfolio ready. 

**Image quality** 
All the images are under 300kb and that was my goal in the end after properly exporting from photoshop and smushing them.

**Responsiveness** 
I worked hard in making my website responsive from 320px to 2500px. Starting my design at the smallest screen and working my way up to the largest.

**Performance** 
I'm deducting a point because my website's speed is a little more than 1 second. As I wanted my images to be more high quality I added extra to the performance budget. Even though I went over the budget a little does not make my website's speed at a snail's pace.

**Code quality** 
I feel like my coding ability is still progressing and I am not giving myself the full point because I am still learning semantics and indentation.

**Comment by thomasjbradley** [comment]
Hahaha! You even branded that last Issue! Well done.
